curl -v --data-urlencode "statement=CREATE TYPE log AS CLOSED{	id:uuid,	host:String,	logname:String,	time:bigint,	method:String,	URL:String,	response:String,	bytes:int};" http://localhost:19002/query/service 

curl -v --data-urlencode "statement= CREATE DATASET nasa_log (log) PRIMARY KEY id AUTOGENERATED;" http://localhost:19002/query/service

#curl -v --data-urlencode "statement=LOAD DATASET nasa_log USING localfs (('path'='127.0.0.1:///home/hdp/Desktop/CS226/Assignment3/nasa.tsv'), ('format'='delimited-text'), ('delimiter'='\t'));" http://localhost:19002/query/service

curl -v --data-urlencode "statement=LOAD DATASET nasa_log USING localfs (('path'='$1'), ('format'='delimited-text'), ('delimiter'='\t'));" http://localhost:19002/query/service

curl -v --data-urlencode "statement=CREATE INDEX timeIDX on nasa_log(time);" http://localhost:19002/query/service


echo "Task A on Asterix DB: " >> taskC.txt

curl -v --data-urlencode "statement=from nasa_log  GROUP BY response select response, avg(bytes);" http://localhost:19002/query/service >> taskC.txt
echo >> taskC.txt


echo "Task B on Asterix DB: " >> taskC.txt

#curl -v --data-urlencode "statement=Select count(*) from nasa_log where time>=804571201 and time<=804571215;" http://localhost:19002/query/service >> taskC.txt

curl -v --data-urlencode "statement=Select count(*) from nasa_log where time>=$2 and time<=$3;" http://localhost:19002/query/service >> taskC.txt

